/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnuvRouteImport } from './routes/anuv'
import { Route as PunjabiRouteImport } from './routes/punjabi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnuvRoute = AnuvRouteImport.update({
  id: '/anuv',
  path: '/anuv',
  getParentRoute: () => rootRouteImport,
} as any)
const PunjabiRoute = PunjabiRouteImport.update({
  id: '/punjabi',
  path: '/punjabi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anuv': typeof AnuvRoute
  '/punjabi': typeof PunjabiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anuv': typeof AnuvRoute
  '/punjabi': typeof PunjabiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anuv': typeof AnuvRoute
  '/punjabi': typeof PunjabiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/anuv' | '/punjabi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anuv' | '/punjabi'
  id: '__root__' | '/' | '/anuv' | '/punjabi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnuvRoute: typeof AnuvRoute
  PunjabiRoute: typeof PunjabiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuv': {
      id: '/anuv'
      path: '/anuv'
      fullPath: '/anuv'
      preLoaderRoute: typeof AnuvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/punjabi': {
      id: '/punjabi'
      path: '/punjabi'
      fullPath: '/punjabi'
      preLoaderRoute: typeof PunjabiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnuvRoute: AnuvRoute,
  PunjabiRoute: PunjabiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
